### ISSUE TITLE
Printable view for process diagrams

### ISSUE THREAD

**Issue by johnblackspear** [ProcessMaker/processmaker#2956]
We need to be able to print BPMN diagrams from the browser.

Suggest we add a new simple, unadorned (no toolbars or buttons) page that is limited to:
 - the process title
 - the diagram
 - (future functionality) other metadata.

We can then choose how to navigate to this page, and end-users can choose how this is printed (e.g. to PDF).

Sub task tickets: 

- [x] [Obtain diagram SVG from BPMN](https://github.com/ProcessMaker/processmaker/issues/2957)
- [x] [Create a print view route & page](https://github.com/ProcessMaker/processmaker/issues/2958)
- [x] [Add documentation to print view](https://github.com/ProcessMaker/processmaker/issues/2959)
