### ISSUE TITLE
Data Sources Changes

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3144]
https://github.com/ProcessMaker/package-data-sources/issues

- [x] https://github.com/ProcessMaker/package-data-sources/issues/76 Inconsistent behavior and UI in screen builder inspector bug
- [x] https://github.com/ProcessMaker/package-data-sources/issues/77 Remove Test Config Button
- [x] https://github.com/ProcessMaker/package-data-sources/issues/78 Remove Get Token Option
- [x] https://github.com/ProcessMaker/package-data-sources/issues/79 Move Endpoints into Own Route
- [x] https://github.com/ProcessMaker/package-data-sources/issues/80 Change Accordion to Tabs
- [x] https://github.com/ProcessMaker/package-data-sources/issues/81 Move Test Endpoint into Tab
- [x] https://github.com/ProcessMaker/package-data-sources/issues/82 New Endpoint Modal
- [x] https://github.com/ProcessMaker/package-data-sources/issues/83 Move SSL Verify Toggle
- [x] https://github.com/ProcessMaker/package-data-sources/issues/84 Change Request Headers Tab

**Comment by velkymx** [comment]
Version 1.0.17 is pending install on release-testing

**Comment by PMQABen** [comment]
New Endpoint Modal #82
Does not redirect to the edit page after a new endpoint is created.

**Comment by PMQABen** [comment]
https://release-testing.processmaker.net/designer/data-sources/3/edit/endpoints/ListAll
Opening this URL has new errors:
```
Vue warn]: Invalid prop: type check failed for prop "value". Expected String with value "", got Array 
found in
---> <MonacoEditor>
       <BTab>
         <BTabs>
           <DetailEndPoint>
             <BTab>
               <BTabs>
                 <Root>

[Vue warn]: Error in mounted hook: "TypeError: factory.create is not a function"
found in
---> <MonacoEditor>
       <BTab>
         <BTabs>
           <DetailEndPoint>
             <BTab>
               <BTabs>
                 <Root>

TypeError: factory.create is not a function
    at createTextBuffer (app-layout.js?id=e31efcb8c498c1c1cf41:396378)
    at new TextModel (app-layout.js?id=e31efcb8c498c1c1cf41:396417)
    at ModelServiceImpl.webpackJsonp../node_modules/monaco-editor/esm/vs/editor/common/services/modelServiceImpl.js.ModelServiceImpl._createModelData (app-layout.js?id=e31efcb8c498c1c1cf41:406072)
    at ModelServiceImpl.webpackJsonp../node_modules/monaco-editor/esm/vs/editor/common/services/modelServiceImpl.js.ModelServiceImpl.createModel (app-layout.js?id=e31efcb8c498c1c1cf41:406086)
    at doCreateModel (app-layout.js?id=e31efcb8c498c1c1cf41:450554)
    at Object.createModel (app-layout.js?id=e31efcb8c498c1c1cf41:450570)
    at new StandaloneEditor (app-layout.js?id=e31efcb8c498c1c1cf41:450213)
    at app-layout.js?id=e31efcb8c498c1c1cf41:450527
    at withAllStandaloneServices (app-layout.js?id=e31efcb8c498c1c1cf41:450514)
    at Object.create (app-layout.js?id=e31efcb8c498c1c1cf41:450526)
```

**Comment by PMQABen** [comment]
After adding a new request header, when clicking the +header button to create another entry, the modal window populates with the selections from the first header. The user has to reload the page to make this not happen.

**Comment by nolanpro** [comment]
Fixed in https://github.com/ProcessMaker/package-data-sources/pull/94

**Comment by nolanpro** [comment]
@PMQABen the console error you're seeing will be fixed in https://github.com/ProcessMaker/package-data-sources/issues/92

The headers are fixed in the above comment link
