### ISSUE TITLE
Collections Bug Fixes

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3145]
https://github.com/ProcessMaker/package-collections/issues

- [ ] #189 Updating only Set Values bug
- [ ] #188 Register as Data Source bug
- [ ] #181 Server throws 500 when a record has data=null on index of records bug
- [ ] #150 Collections List Icon Mouse Over bug
- [ ] #149 No Permission? Hide Create Button bug
- [ ] #148 Multi-page Record Form bug
